#!/bin/bash
config=(
    openbox
    alacritty.yml
    tint2
    rofi
    dunst
    nvim
    polybar
)

home=(
    #.bashrc
    .vim
    .vimrc
)

for thing in "${config[@]}"; do
    cp -r $HOME/.config/$thing config/
done

for thing in "${home[@]}"; do
    cp -r $HOME/$thing home/
done

cp $HOME/.local/share/nvim/site/autoload/plug.vim plug.vim
