#!/bin/sh
killall -q polybar
env XSECURELOCK_COMPOSITE_OBSCURER=0 XSECURELOCK_DISCARD_FIRST_KEYPRESS=0 \
    XSECURELOCK_NO_COMPOSITE=1 XSECURELOCK_SAVER=saver_blank \
    XSECURELOCK_IMAGE_DURATION_SECONDS=9999 \
    XSECURELOCK_BLANK_TIMEOUT=10 \
    XSECURELOCK_BLANK_DPMS_STATE=suspend \
    XSECURELOCK_LIST_VIDEOS_COMMAND="find ~/Pictures/screensaver -type f" \
    XSECURELOCK_SHOW_DATETIME=1 XSECURELOCK_SHOW_HOSTNAME=1 xsecurelock
$HOME/.config/polybar/launch.sh &
